# Generated by Django 4.2.6 on 2023-11-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название новости')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Загрузите фото')),
                ('description', models.TextField(verbose_name='Полная новость')),
                ('type_news', models.CharField(choices=[('Политика', 'Политика'), ('Шоубизнес', 'Шоубизнес'), ('Спорт', 'Спорт')], max_length=10, verbose_name='Выберите тип новостей')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
    ]
